// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: proto/lead_template/lead_template.proto

package go_micro_service_lead_template

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AllLeadTemplateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AllLeadTemplateRequest) Reset() {
	*x = AllLeadTemplateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lead_template_lead_template_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllLeadTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllLeadTemplateRequest) ProtoMessage() {}

func (x *AllLeadTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_template_lead_template_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllLeadTemplateRequest.ProtoReflect.Descriptor instead.
func (*AllLeadTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_lead_template_lead_template_proto_rawDescGZIP(), []int{0}
}

func (x *AllLeadTemplateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type NewLeadTemplateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string                             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	KeyValueTypes []*NewLeadTemplateRequest_KeyValue `protobuf:"bytes,2,rep,name=keyValueTypes,proto3" json:"keyValueTypes,omitempty"`
}

func (x *NewLeadTemplateRequest) Reset() {
	*x = NewLeadTemplateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lead_template_lead_template_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewLeadTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLeadTemplateRequest) ProtoMessage() {}

func (x *NewLeadTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_template_lead_template_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLeadTemplateRequest.ProtoReflect.Descriptor instead.
func (*NewLeadTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_lead_template_lead_template_proto_rawDescGZIP(), []int{1}
}

func (x *NewLeadTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewLeadTemplateRequest) GetKeyValueTypes() []*NewLeadTemplateRequest_KeyValue {
	if x != nil {
		return x.KeyValueTypes
	}
	return nil
}

type NewLeadTemplateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status  bool   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *NewLeadTemplateResponse) Reset() {
	*x = NewLeadTemplateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lead_template_lead_template_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewLeadTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLeadTemplateResponse) ProtoMessage() {}

func (x *NewLeadTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_template_lead_template_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLeadTemplateResponse.ProtoReflect.Descriptor instead.
func (*NewLeadTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_lead_template_lead_template_proto_rawDescGZIP(), []int{2}
}

func (x *NewLeadTemplateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NewLeadTemplateResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type LeadTemplateByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId string `protobuf:"bytes,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
}

func (x *LeadTemplateByIdRequest) Reset() {
	*x = LeadTemplateByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lead_template_lead_template_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeadTemplateByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadTemplateByIdRequest) ProtoMessage() {}

func (x *LeadTemplateByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_template_lead_template_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadTemplateByIdRequest.ProtoReflect.Descriptor instead.
func (*LeadTemplateByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_lead_template_lead_template_proto_rawDescGZIP(), []int{3}
}

func (x *LeadTemplateByIdRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type LeadTemplateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string                           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	KeyValueTypes []*LeadTemplateResponse_KeyValue `protobuf:"bytes,3,rep,name=keyValueTypes,proto3" json:"keyValueTypes,omitempty"`
}

func (x *LeadTemplateResponse) Reset() {
	*x = LeadTemplateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lead_template_lead_template_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeadTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadTemplateResponse) ProtoMessage() {}

func (x *LeadTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_template_lead_template_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadTemplateResponse.ProtoReflect.Descriptor instead.
func (*LeadTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_lead_template_lead_template_proto_rawDescGZIP(), []int{4}
}

func (x *LeadTemplateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LeadTemplateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeadTemplateResponse) GetKeyValueTypes() []*LeadTemplateResponse_KeyValue {
	if x != nil {
		return x.KeyValueTypes
	}
	return nil
}

type LeadTemplateListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeadTemplates []*LeadTemplateResponse `protobuf:"bytes,1,rep,name=leadTemplates,proto3" json:"leadTemplates,omitempty"`
}

func (x *LeadTemplateListResponse) Reset() {
	*x = LeadTemplateListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lead_template_lead_template_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeadTemplateListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadTemplateListResponse) ProtoMessage() {}

func (x *LeadTemplateListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_template_lead_template_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadTemplateListResponse.ProtoReflect.Descriptor instead.
func (*LeadTemplateListResponse) Descriptor() ([]byte, []int) {
	return file_proto_lead_template_lead_template_proto_rawDescGZIP(), []int{5}
}

func (x *LeadTemplateListResponse) GetLeadTemplates() []*LeadTemplateResponse {
	if x != nil {
		return x.LeadTemplates
	}
	return nil
}

type NewLeadTemplateRequest_KeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueType string `protobuf:"bytes,2,opt,name=valueType,proto3" json:"valueType,omitempty"`
}

func (x *NewLeadTemplateRequest_KeyValue) Reset() {
	*x = NewLeadTemplateRequest_KeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lead_template_lead_template_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewLeadTemplateRequest_KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLeadTemplateRequest_KeyValue) ProtoMessage() {}

func (x *NewLeadTemplateRequest_KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_template_lead_template_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLeadTemplateRequest_KeyValue.ProtoReflect.Descriptor instead.
func (*NewLeadTemplateRequest_KeyValue) Descriptor() ([]byte, []int) {
	return file_proto_lead_template_lead_template_proto_rawDescGZIP(), []int{1, 0}
}

func (x *NewLeadTemplateRequest_KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *NewLeadTemplateRequest_KeyValue) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

type LeadTemplateResponse_KeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueType string `protobuf:"bytes,2,opt,name=valueType,proto3" json:"valueType,omitempty"`
}

func (x *LeadTemplateResponse_KeyValue) Reset() {
	*x = LeadTemplateResponse_KeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lead_template_lead_template_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeadTemplateResponse_KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadTemplateResponse_KeyValue) ProtoMessage() {}

func (x *LeadTemplateResponse_KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_template_lead_template_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadTemplateResponse_KeyValue.ProtoReflect.Descriptor instead.
func (*LeadTemplateResponse_KeyValue) Descriptor() ([]byte, []int) {
	return file_proto_lead_template_lead_template_proto_rawDescGZIP(), []int{4, 0}
}

func (x *LeadTemplateResponse_KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LeadTemplateResponse_KeyValue) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

var File_proto_lead_template_lead_template_proto protoreflect.FileDescriptor

var file_proto_lead_template_lead_template_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x65, 0x61, 0x64, 0x5f, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x6c, 0x65, 0x61, 0x64, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x67, 0x6f, 0x2e, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x61, 0x64,
	0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x22, 0x30, 0x0a, 0x16, 0x41, 0x6c, 0x6c,
	0x4c, 0x65, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xcf, 0x01, 0x0a, 0x16,
	0x4e, 0x65, 0x77, 0x4c, 0x65, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x65, 0x0a, 0x0d, 0x6b, 0x65,
	0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x3f, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x2e, 0x4e, 0x65, 0x77, 0x4c, 0x65, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x0d, 0x6b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x1a, 0x3a, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x1c, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4b, 0x0a,
	0x17, 0x4e, 0x65, 0x77, 0x4c, 0x65, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x39, 0x0a, 0x17, 0x4c, 0x65,
	0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x49, 0x64, 0x22, 0xdb, 0x01, 0x0a, 0x14, 0x4c, 0x65, 0x61, 0x64, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x63, 0x0a, 0x0d, 0x6b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x67, 0x6f, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x61,
	0x64, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0d, 0x6b, 0x65, 0x79, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x3a, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x76, 0x0a, 0x18, 0x4c, 0x65, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5a, 0x0a, 0x0d, 0x6c, 0x65, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x5f, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0d, 0x6c, 0x65,
	0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x32, 0xff, 0x02, 0x0a, 0x0d,
	0x4c, 0x65, 0x61, 0x64, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x7b, 0x0a,
	0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x36, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x5f,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x4e, 0x65, 0x77, 0x4c, 0x65, 0x61, 0x64,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x37, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x2e, 0x4e, 0x65, 0x77, 0x4c, 0x65, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x76, 0x0a, 0x03, 0x67, 0x65,
	0x74, 0x12, 0x37, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x67, 0x6f, 0x2e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6c, 0x65,
	0x61, 0x64, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x4c, 0x65, 0x61, 0x64,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x79, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x12, 0x36, 0x2e, 0x67, 0x6f, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x61,
	0x64, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x6c, 0x6c, 0x4c, 0x65,
	0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x38, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_lead_template_lead_template_proto_rawDescOnce sync.Once
	file_proto_lead_template_lead_template_proto_rawDescData = file_proto_lead_template_lead_template_proto_rawDesc
)

func file_proto_lead_template_lead_template_proto_rawDescGZIP() []byte {
	file_proto_lead_template_lead_template_proto_rawDescOnce.Do(func() {
		file_proto_lead_template_lead_template_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lead_template_lead_template_proto_rawDescData)
	})
	return file_proto_lead_template_lead_template_proto_rawDescData
}

var file_proto_lead_template_lead_template_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_lead_template_lead_template_proto_goTypes = []interface{}{
	(*AllLeadTemplateRequest)(nil),          // 0: go.micro.service.lead_template.AllLeadTemplateRequest
	(*NewLeadTemplateRequest)(nil),          // 1: go.micro.service.lead_template.NewLeadTemplateRequest
	(*NewLeadTemplateResponse)(nil),         // 2: go.micro.service.lead_template.NewLeadTemplateResponse
	(*LeadTemplateByIdRequest)(nil),         // 3: go.micro.service.lead_template.LeadTemplateByIdRequest
	(*LeadTemplateResponse)(nil),            // 4: go.micro.service.lead_template.LeadTemplateResponse
	(*LeadTemplateListResponse)(nil),        // 5: go.micro.service.lead_template.LeadTemplateListResponse
	(*NewLeadTemplateRequest_KeyValue)(nil), // 6: go.micro.service.lead_template.NewLeadTemplateRequest.KeyValue
	(*LeadTemplateResponse_KeyValue)(nil),   // 7: go.micro.service.lead_template.LeadTemplateResponse.KeyValue
}
var file_proto_lead_template_lead_template_proto_depIdxs = []int32{
	6, // 0: go.micro.service.lead_template.NewLeadTemplateRequest.keyValueTypes:type_name -> go.micro.service.lead_template.NewLeadTemplateRequest.KeyValue
	7, // 1: go.micro.service.lead_template.LeadTemplateResponse.keyValueTypes:type_name -> go.micro.service.lead_template.LeadTemplateResponse.KeyValue
	4, // 2: go.micro.service.lead_template.LeadTemplateListResponse.leadTemplates:type_name -> go.micro.service.lead_template.LeadTemplateResponse
	1, // 3: go.micro.service.lead_template.Lead_template.create:input_type -> go.micro.service.lead_template.NewLeadTemplateRequest
	3, // 4: go.micro.service.lead_template.Lead_template.get:input_type -> go.micro.service.lead_template.LeadTemplateByIdRequest
	0, // 5: go.micro.service.lead_template.Lead_template.all:input_type -> go.micro.service.lead_template.AllLeadTemplateRequest
	2, // 6: go.micro.service.lead_template.Lead_template.create:output_type -> go.micro.service.lead_template.NewLeadTemplateResponse
	4, // 7: go.micro.service.lead_template.Lead_template.get:output_type -> go.micro.service.lead_template.LeadTemplateResponse
	5, // 8: go.micro.service.lead_template.Lead_template.all:output_type -> go.micro.service.lead_template.LeadTemplateListResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_lead_template_lead_template_proto_init() }
func file_proto_lead_template_lead_template_proto_init() {
	if File_proto_lead_template_lead_template_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lead_template_lead_template_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllLeadTemplateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lead_template_lead_template_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewLeadTemplateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lead_template_lead_template_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewLeadTemplateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lead_template_lead_template_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeadTemplateByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lead_template_lead_template_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeadTemplateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lead_template_lead_template_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeadTemplateListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lead_template_lead_template_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewLeadTemplateRequest_KeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lead_template_lead_template_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeadTemplateResponse_KeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lead_template_lead_template_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lead_template_lead_template_proto_goTypes,
		DependencyIndexes: file_proto_lead_template_lead_template_proto_depIdxs,
		MessageInfos:      file_proto_lead_template_lead_template_proto_msgTypes,
	}.Build()
	File_proto_lead_template_lead_template_proto = out.File
	file_proto_lead_template_lead_template_proto_rawDesc = nil
	file_proto_lead_template_lead_template_proto_goTypes = nil
	file_proto_lead_template_lead_template_proto_depIdxs = nil
}
