// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/lead_template/lead_template.proto

package go_micro_service_lead_template

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AllLeadTemplateRequest struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllLeadTemplateRequest) Reset()         { *m = AllLeadTemplateRequest{} }
func (m *AllLeadTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*AllLeadTemplateRequest) ProtoMessage()    {}
func (*AllLeadTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1798374069df5181, []int{0}
}

func (m *AllLeadTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllLeadTemplateRequest.Unmarshal(m, b)
}
func (m *AllLeadTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllLeadTemplateRequest.Marshal(b, m, deterministic)
}
func (m *AllLeadTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllLeadTemplateRequest.Merge(m, src)
}
func (m *AllLeadTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_AllLeadTemplateRequest.Size(m)
}
func (m *AllLeadTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllLeadTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllLeadTemplateRequest proto.InternalMessageInfo

func (m *AllLeadTemplateRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type NewLeadTemplateRequest struct {
	Name                 string                             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	KeyValueTypes        []*NewLeadTemplateRequest_KeyValue `protobuf:"bytes,2,rep,name=keyValueTypes,proto3" json:"keyValueTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *NewLeadTemplateRequest) Reset()         { *m = NewLeadTemplateRequest{} }
func (m *NewLeadTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*NewLeadTemplateRequest) ProtoMessage()    {}
func (*NewLeadTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1798374069df5181, []int{1}
}

func (m *NewLeadTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewLeadTemplateRequest.Unmarshal(m, b)
}
func (m *NewLeadTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewLeadTemplateRequest.Marshal(b, m, deterministic)
}
func (m *NewLeadTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewLeadTemplateRequest.Merge(m, src)
}
func (m *NewLeadTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_NewLeadTemplateRequest.Size(m)
}
func (m *NewLeadTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewLeadTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewLeadTemplateRequest proto.InternalMessageInfo

func (m *NewLeadTemplateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewLeadTemplateRequest) GetKeyValueTypes() []*NewLeadTemplateRequest_KeyValue {
	if m != nil {
		return m.KeyValueTypes
	}
	return nil
}

type NewLeadTemplateRequest_KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueType            string   `protobuf:"bytes,2,opt,name=valueType,proto3" json:"valueType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewLeadTemplateRequest_KeyValue) Reset()         { *m = NewLeadTemplateRequest_KeyValue{} }
func (m *NewLeadTemplateRequest_KeyValue) String() string { return proto.CompactTextString(m) }
func (*NewLeadTemplateRequest_KeyValue) ProtoMessage()    {}
func (*NewLeadTemplateRequest_KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_1798374069df5181, []int{1, 0}
}

func (m *NewLeadTemplateRequest_KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewLeadTemplateRequest_KeyValue.Unmarshal(m, b)
}
func (m *NewLeadTemplateRequest_KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewLeadTemplateRequest_KeyValue.Marshal(b, m, deterministic)
}
func (m *NewLeadTemplateRequest_KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewLeadTemplateRequest_KeyValue.Merge(m, src)
}
func (m *NewLeadTemplateRequest_KeyValue) XXX_Size() int {
	return xxx_messageInfo_NewLeadTemplateRequest_KeyValue.Size(m)
}
func (m *NewLeadTemplateRequest_KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_NewLeadTemplateRequest_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_NewLeadTemplateRequest_KeyValue proto.InternalMessageInfo

func (m *NewLeadTemplateRequest_KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *NewLeadTemplateRequest_KeyValue) GetValueType() string {
	if m != nil {
		return m.ValueType
	}
	return ""
}

type NewLeadTemplateResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewLeadTemplateResponse) Reset()         { *m = NewLeadTemplateResponse{} }
func (m *NewLeadTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*NewLeadTemplateResponse) ProtoMessage()    {}
func (*NewLeadTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1798374069df5181, []int{2}
}

func (m *NewLeadTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewLeadTemplateResponse.Unmarshal(m, b)
}
func (m *NewLeadTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewLeadTemplateResponse.Marshal(b, m, deterministic)
}
func (m *NewLeadTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewLeadTemplateResponse.Merge(m, src)
}
func (m *NewLeadTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_NewLeadTemplateResponse.Size(m)
}
func (m *NewLeadTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewLeadTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewLeadTemplateResponse proto.InternalMessageInfo

func (m *NewLeadTemplateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *NewLeadTemplateResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type LeadTemplateByIdRequest struct {
	TemplateId           string   `protobuf:"bytes,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeadTemplateByIdRequest) Reset()         { *m = LeadTemplateByIdRequest{} }
func (m *LeadTemplateByIdRequest) String() string { return proto.CompactTextString(m) }
func (*LeadTemplateByIdRequest) ProtoMessage()    {}
func (*LeadTemplateByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1798374069df5181, []int{3}
}

func (m *LeadTemplateByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeadTemplateByIdRequest.Unmarshal(m, b)
}
func (m *LeadTemplateByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeadTemplateByIdRequest.Marshal(b, m, deterministic)
}
func (m *LeadTemplateByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeadTemplateByIdRequest.Merge(m, src)
}
func (m *LeadTemplateByIdRequest) XXX_Size() int {
	return xxx_messageInfo_LeadTemplateByIdRequest.Size(m)
}
func (m *LeadTemplateByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeadTemplateByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeadTemplateByIdRequest proto.InternalMessageInfo

func (m *LeadTemplateByIdRequest) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

type LeadTemplateResponse struct {
	Id                   string                           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	KeyValueTypes        []*LeadTemplateResponse_KeyValue `protobuf:"bytes,3,rep,name=keyValueTypes,proto3" json:"keyValueTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *LeadTemplateResponse) Reset()         { *m = LeadTemplateResponse{} }
func (m *LeadTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*LeadTemplateResponse) ProtoMessage()    {}
func (*LeadTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1798374069df5181, []int{4}
}

func (m *LeadTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeadTemplateResponse.Unmarshal(m, b)
}
func (m *LeadTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeadTemplateResponse.Marshal(b, m, deterministic)
}
func (m *LeadTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeadTemplateResponse.Merge(m, src)
}
func (m *LeadTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_LeadTemplateResponse.Size(m)
}
func (m *LeadTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeadTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeadTemplateResponse proto.InternalMessageInfo

func (m *LeadTemplateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LeadTemplateResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LeadTemplateResponse) GetKeyValueTypes() []*LeadTemplateResponse_KeyValue {
	if m != nil {
		return m.KeyValueTypes
	}
	return nil
}

type LeadTemplateResponse_KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueType            string   `protobuf:"bytes,2,opt,name=valueType,proto3" json:"valueType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeadTemplateResponse_KeyValue) Reset()         { *m = LeadTemplateResponse_KeyValue{} }
func (m *LeadTemplateResponse_KeyValue) String() string { return proto.CompactTextString(m) }
func (*LeadTemplateResponse_KeyValue) ProtoMessage()    {}
func (*LeadTemplateResponse_KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_1798374069df5181, []int{4, 0}
}

func (m *LeadTemplateResponse_KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeadTemplateResponse_KeyValue.Unmarshal(m, b)
}
func (m *LeadTemplateResponse_KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeadTemplateResponse_KeyValue.Marshal(b, m, deterministic)
}
func (m *LeadTemplateResponse_KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeadTemplateResponse_KeyValue.Merge(m, src)
}
func (m *LeadTemplateResponse_KeyValue) XXX_Size() int {
	return xxx_messageInfo_LeadTemplateResponse_KeyValue.Size(m)
}
func (m *LeadTemplateResponse_KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_LeadTemplateResponse_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_LeadTemplateResponse_KeyValue proto.InternalMessageInfo

func (m *LeadTemplateResponse_KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LeadTemplateResponse_KeyValue) GetValueType() string {
	if m != nil {
		return m.ValueType
	}
	return ""
}

type LeadTemplateListResponse struct {
	LeadTemplates        []*LeadTemplateResponse `protobuf:"bytes,1,rep,name=leadTemplates,proto3" json:"leadTemplates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *LeadTemplateListResponse) Reset()         { *m = LeadTemplateListResponse{} }
func (m *LeadTemplateListResponse) String() string { return proto.CompactTextString(m) }
func (*LeadTemplateListResponse) ProtoMessage()    {}
func (*LeadTemplateListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1798374069df5181, []int{5}
}

func (m *LeadTemplateListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeadTemplateListResponse.Unmarshal(m, b)
}
func (m *LeadTemplateListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeadTemplateListResponse.Marshal(b, m, deterministic)
}
func (m *LeadTemplateListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeadTemplateListResponse.Merge(m, src)
}
func (m *LeadTemplateListResponse) XXX_Size() int {
	return xxx_messageInfo_LeadTemplateListResponse.Size(m)
}
func (m *LeadTemplateListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeadTemplateListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeadTemplateListResponse proto.InternalMessageInfo

func (m *LeadTemplateListResponse) GetLeadTemplates() []*LeadTemplateResponse {
	if m != nil {
		return m.LeadTemplates
	}
	return nil
}

func init() {
	proto.RegisterType((*AllLeadTemplateRequest)(nil), "go.micro.service.lead_template.AllLeadTemplateRequest")
	proto.RegisterType((*NewLeadTemplateRequest)(nil), "go.micro.service.lead_template.NewLeadTemplateRequest")
	proto.RegisterType((*NewLeadTemplateRequest_KeyValue)(nil), "go.micro.service.lead_template.NewLeadTemplateRequest.KeyValue")
	proto.RegisterType((*NewLeadTemplateResponse)(nil), "go.micro.service.lead_template.NewLeadTemplateResponse")
	proto.RegisterType((*LeadTemplateByIdRequest)(nil), "go.micro.service.lead_template.LeadTemplateByIdRequest")
	proto.RegisterType((*LeadTemplateResponse)(nil), "go.micro.service.lead_template.LeadTemplateResponse")
	proto.RegisterType((*LeadTemplateResponse_KeyValue)(nil), "go.micro.service.lead_template.LeadTemplateResponse.KeyValue")
	proto.RegisterType((*LeadTemplateListResponse)(nil), "go.micro.service.lead_template.LeadTemplateListResponse")
}

func init() {
	proto.RegisterFile("proto/lead_template/lead_template.proto", fileDescriptor_1798374069df5181)
}

var fileDescriptor_1798374069df5181 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x41, 0x4b, 0xeb, 0x40,
	0x10, 0x6e, 0x92, 0x47, 0x5f, 0x3b, 0x8f, 0x3e, 0x64, 0x91, 0x36, 0x04, 0x29, 0x25, 0x17, 0x7b,
	0x8a, 0x52, 0xc5, 0xaa, 0x20, 0xa2, 0xb7, 0xd2, 0xe2, 0x21, 0x14, 0x0f, 0x5e, 0x64, 0x4d, 0x86,
	0x12, 0xba, 0x69, 0x62, 0x76, 0x1b, 0x09, 0xfe, 0x48, 0x7f, 0x80, 0x3f, 0x46, 0x49, 0x4c, 0xea,
	0x46, 0x83, 0xa5, 0x05, 0x6f, 0x33, 0x93, 0x99, 0x6f, 0xbe, 0xef, 0xcb, 0xb0, 0xb0, 0x1f, 0x46,
	0x81, 0x08, 0x0e, 0x18, 0x52, 0xf7, 0x5e, 0xa0, 0x1f, 0x32, 0x2a, 0xb0, 0x9c, 0x59, 0x59, 0x07,
	0xe9, 0xce, 0x02, 0xcb, 0xf7, 0x9c, 0x28, 0xb0, 0x38, 0x46, 0xb1, 0xe7, 0xa0, 0x55, 0xea, 0x32,
	0x0f, 0xa1, 0x7d, 0xc5, 0xd8, 0x04, 0xa9, 0x3b, 0xcd, 0x4b, 0x36, 0x3e, 0x2e, 0x91, 0x0b, 0xd2,
	0x86, 0x3a, 0x17, 0x54, 0x2c, 0xb9, 0xae, 0xf4, 0x94, 0x7e, 0xd3, 0xce, 0x33, 0xf3, 0x45, 0x81,
	0xf6, 0x0d, 0x3e, 0x55, 0x8d, 0x10, 0xf8, 0xb3, 0xa0, 0x3e, 0xe6, 0x03, 0x59, 0x4c, 0x10, 0x5a,
	0x73, 0x4c, 0x6e, 0x29, 0x5b, 0xe2, 0x34, 0x09, 0x91, 0xeb, 0x6a, 0x4f, 0xeb, 0xff, 0x1b, 0x5c,
	0x5a, 0x3f, 0x13, 0xb3, 0xaa, 0x57, 0x58, 0xe3, 0x1c, 0xcb, 0x2e, 0xa3, 0x1a, 0xe7, 0xd0, 0x28,
	0x3e, 0x91, 0x1d, 0xd0, 0xe6, 0x98, 0xe4, 0x2c, 0xd2, 0x90, 0xec, 0x41, 0x33, 0x2e, 0x7a, 0x75,
	0x35, 0xab, 0x7f, 0x16, 0xcc, 0x31, 0x74, 0xbe, 0x6d, 0xe3, 0x61, 0xb0, 0xe0, 0x48, 0x74, 0xf8,
	0xeb, 0x23, 0xe7, 0x74, 0x56, 0x88, 0x2a, 0x52, 0xc9, 0x9e, 0x14, 0xaf, 0xb1, 0xb2, 0xe7, 0x0c,
	0x3a, 0x32, 0xd2, 0x75, 0x32, 0x72, 0x0b, 0x7b, 0xba, 0x00, 0x85, 0xbc, 0x91, 0x9b, 0xe3, 0x49,
	0x15, 0xf3, 0x55, 0x81, 0xdd, 0x4a, 0x16, 0xff, 0x41, 0xf5, 0x8a, 0x01, 0xd5, 0x73, 0x57, 0x3e,
	0xab, 0x92, 0xcf, 0xce, 0x57, 0x9f, 0xb5, 0xcc, 0xe7, 0x8b, 0x75, 0x3e, 0x57, 0x2d, 0xfc, 0x15,
	0x97, 0x63, 0xd0, 0xe5, 0x5d, 0x13, 0x8f, 0x8b, 0x95, 0xc0, 0x3b, 0x68, 0x31, 0xe9, 0x5b, 0x7a,
	0x72, 0x29, 0xf9, 0xe3, 0x6d, 0xc8, 0xdb, 0x65, 0xa8, 0xc1, 0x9b, 0x0a, 0xad, 0x89, 0x3c, 0x45,
	0x9e, 0xa1, 0xee, 0x44, 0x98, 0x46, 0x27, 0xdb, 0x5d, 0xa1, 0x31, 0xdc, 0x78, 0xee, 0x83, 0x9b,
	0x59, 0x23, 0x31, 0x68, 0x33, 0x14, 0x64, 0xb8, 0x89, 0x34, 0xe9, 0x88, 0x8c, 0xad, 0x3c, 0x31,
	0x6b, 0x24, 0x01, 0x8d, 0x32, 0xb6, 0x5e, 0x71, 0xf5, 0x6b, 0x60, 0x9c, 0x6e, 0xb2, 0x56, 0xfe,
	0xb7, 0x66, 0xed, 0xa1, 0x9e, 0x3d, 0x45, 0x47, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0x73, 0xb6,
	0x74, 0x73, 0xb5, 0x04, 0x00, 0x00,
}
